#!/bin/bash

###
#
# WLTest
# Testing tool for uWaterloo CS 241 assignments 9 and 10
# Copyright (c) 2011 Eli Spiro
# Made available under the GNU General Public Licence v3 — see README
#
###

function quitline {
	echo ""
	exit
}

echo ""
echo "WLTest, by Eli Spiro"
echo "Usage: WLTest [-c] [-i] file"
echo "Compiles file.wl into a MIPS machine code program and runs it"
echo "-c to recompile WLGen.java, -i to leave intermediate files after they're created"
echo ""

if [[ $1 == '-c' ]]
	then
	echo "Compiling WLGen..."
	javac WLGen.java
	shift 1
fi

if [[ $1 == '-i' ]]
	then
	clean=0
	shift 1
else
	clean=1
fi

echo "Scanning WL code..."
java cs241.WLScan < $1.wl > $1.scanned
if [[ $? == 1 ]]
	then
	echo "An error occurred while scanning."
	quitline
fi

echo "Parsing WL tokens..."
java cs241.WLParse < $1.scanned > $1.wli
if [[ $? == 1 ]]
	then
	echo "An error occurred while parsing."
	quitline
fi

echo "Generating MIPS code..."
java WLGen < $1.wli > $1.asm
if [[ $? == 1 ]]
	then
	echo "An error occurred while generating code."
	quitline
fi

echo "Assembling MIPS machine code..."
java cs241.binasm < $1.asm > $1.mips
if [[ $? == 1 ]]
	then
	echo "An error occurred while assembling."
	quitline
fi

echo "Running MIPS program, input from mips.in"
echo ""
java mips.twoints $1.mips < mips.in
echo ""

if [[ $clean == 1 ]]
	then
	rm $1.scanned
	rm $1.wli
	rm $1.asm
	rm $1.mips
fi